### ISSUE TITLE
E: Package 'libcurl3' has no installation candidate

### ISSUE THREAD

**Issue by cu-18bcs1637** [mesos/mesos-packaging#1]
I am trying to install all the required dependencies for mesos. However, I am getting this error for <code>libcurl3</code>. 

<img width="1078" alt="Screenshot 2022-03-21 at 12 32 56 AM" src="https://user-images.githubusercontent.com/55397457/159178616-3768e51e-5c48-4de0-bb68-de21cc62484f.png">

I am using <code>Ubuntu 20.04.4 LTS (Focal Fossa)</code>

So, should I go with installing <code>libcurl4</code> or <code>libcurl3-nss</code>?

**Comment by cf-natali** [comment]
Trying installing `libcurl4` and let me know how it goes.

**Comment by cu-18bcs1637** [comment]
@cf-natali I tried <code>libcurl3-nss</code>. This one worked.

But this command didn't worked <code>sudo gem install fpm</code> I am getting this error:
<img width="967" alt="Screenshot 2022-03-23 at 10 57 00 AM" src="https://user-images.githubusercontent.com/55397457/159630250-25327b82-e458-4590-8b8a-b161e7083a67.png">


How can I fix this?

**Comment by ridv** [comment]
Looks like your system can't reach the ruby gems repository. Looks like a firewall issue.

**Comment by cu-18bcs1637** [comment]
@ridv How can I resolve this? I searched this on google most of the fixes I saw is saying to disable IPv6. But I don't have any IPv6 configured in my machine.

**Comment by cf-natali** [comment]
Just backing up for a second, which instructions are you using?
Can't really see why `sudo gem install fpm` would be needed.

**Comment by ridv** [comment]
@cf-natali they're using the instructions in the README. [fpm](https://fpm.readthedocs.io/en/v1.14.1/) is what's used to generate the packages

The package building script `build_mesos` uses it.

@cu-18bcs1637 unfortunately there could be so many reasons why your system can't reach the ruby gems repository. The only piece of advice I can give you is to try to visit https://rubygems.org/specs.4.8.gz on your browser and seeing if that works. If it does, you'll have to dig deeper into why `gem` can't reach it.

**Comment by cu-18bcs1637** [comment]
@ridv I am trying to figuring out the fix for the issue.

**Comment by ridv** [comment]
Just tested it on an ubuntu focal container on docker. No issues installing:

```
root@6901f40c2f8f:/etc/ssl/certs# gem install fpm
Fetching cabin-0.9.0.gem
Fetching backports-3.23.0.gem
Fetching arr-pm-0.0.11.gem
Fetching clamp-1.0.1.gem
Fetching stud-0.0.23.gem
Fetching mustache-0.99.8.gem
Fetching insist-1.0.0.gem
Fetching dotenv-2.7.6.gem
Fetching fpm-1.14.1.gem
Fetching pleaserun-0.0.32.gem
Fetching rchardet-1.8.0.gem
Fetching git-1.10.2.gem
Successfully installed cabin-0.9.0
Successfully installed backports-3.23.0
Successfully installed arr-pm-0.0.11
Successfully installed clamp-1.0.1
Successfully installed stud-0.0.23
Successfully installed mustache-0.99.8
Successfully installed insist-1.0.0
Successfully installed dotenv-2.7.6
Successfully installed pleaserun-0.0.32
Successfully installed rchardet-1.8.0
Successfully installed git-1.10.2
Successfully installed fpm-1.14.1
Parsing documentation for cabin-0.9.0
Installing ri documentation for cabin-0.9.0
Parsing documentation for backports-3.23.0
Installing ri documentation for backports-3.23.0
Parsing documentation for arr-pm-0.0.11
Installing ri documentation for arr-pm-0.0.11
Parsing documentation for clamp-1.0.1
Installing ri documentation for clamp-1.0.1
Parsing documentation for stud-0.0.23
Installing ri documentation for stud-0.0.23
Parsing documentation for mustache-0.99.8
Installing ri documentation for mustache-0.99.8
Parsing documentation for insist-1.0.0
Installing ri documentation for insist-1.0.0
Parsing documentation for dotenv-2.7.6
Installing ri documentation for dotenv-2.7.6
Parsing documentation for pleaserun-0.0.32
Installing ri documentation for pleaserun-0.0.32
Parsing documentation for rchardet-1.8.0
Installing ri documentation for rchardet-1.8.0
Parsing documentation for git-1.10.2
Installing ri documentation for git-1.10.2
Parsing documentation for fpm-1.14.1
Installing ri documentation for fpm-1.14.1
Done installing documentation for cabin, backports, arr-pm, clamp, stud, mustache, insist, dotenv, pleaserun, rchardet, git, fpm after 3 seconds
12 gems installed
```
Thanks for your original report, we've fixed it in https://github.com/mesos/mesos-packaging/commit/dad6e48d5bc6c2f15470c94fe06ddfda2cbdf57a

Unfortunately, figuring out why a dependency, such as a ruby gem, can't be installed on a particular machine is out of the scope of this project so I'll be closing this issue as we've addressed the original problem.

**Comment by cf-natali** [comment]
Thanks @ridv !
